DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS admins;

CREATE TABLE tokens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  token TEXT NOT NULL,
  secret TEXT NOT NULL,
  datetime DATE
);

CREATE TABLE admin (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username INTEGER NOT NULL,
  password TEXT NOT NULL
);